driver:
  name: vagrant

platforms:
  - name: bento/debian-9

provisioner:
  salt_version: latest
  name: salt_solo
  formula: pcs
  require_chef: false
  pillars-from-files:
    pcs.sls: pillar.example

suites:
  - name: node1
    driver:
       network:
         - ["private_network", {ip: "10.0.0.101"}]
         - ["private_network", {ip: "10.0.1.101"}]
    provisioner:
      state_top:
        base:
          '*':
            - pcs.patch_states_pcs
            - pcs.patch_states_user
            - pcs
            - pcs.resources
      pillars:
        top.sls:
          base:
            '*':
               - pcs
  - name: node2
    driver:
       network:
         - ["private_network", {ip: "10.0.0.102"}]
         - ["private_network", {ip: "10.0.1.102"}]
    provisioner:
      state_top:
        base:
          '*':
            - pcs.patch_states_pcs
            - pcs.patch_states_user
            - pcs
            - pcs.resources
      pillars:
        top.sls:
          base:
            '*':
               - pcs

  - name: node3
    driver:
       network:
         - ["private_network", {ip: "10.0.0.103"}]
         - ["private_network", {ip: "10.0.1.103"}]
    provisioner:
      state_top:
        base:
          '*':
            - pcs.patch_states_pcs
            - pcs.patch_states_user
            - pcs
            - pcs.resources
      pillars:
        top.sls:
          base:
            '*':
               - pcs

# echo -e "10.0.0.101 node1-bento-debian-9.vagrantup.com\n10.0.0.102 node2-bento-debian-9.vagrantup.com\n10.0.0.103 node3-bento-debian-9.vagrantup.com\n" >> /etc/hosts
# echo -e "10.0.1.101 ha.node1-bento-debian-9.vagrantup.com\n10.0.1.102 ha.node2-bento-debian-9.vagrantup.com\n10.0.1.103 ha.node3-bento-debian-9.vagrantup.com\n" >> /etc/hosts
# sed -i s/[a-z0-9-]*.vagrantup.com\\t//g /etc/hosts
# salt-call --config-dir=/tmp/kitchen/etc/salt --local state.apply pcs.orchestration
