driver:
  name: vagrant

platforms:
  - name: bento/debian-9

provisioner:
  salt_version: latest
  name: salt_solo
  formula: pcs
  require_chef: false
  pillars-from-files:
    pcs.sls: pillar.example

suites:
  - name: server
    provisioner:
      state_top:
        base:
          '*':
            - pcs
      pillars:
        top.sls:
          base:
            '*':
               - pcs

